version: "3"

services:
  emqx:
    image: emqx:5.8.1
    container_name: emqx
    environment:
      - "EMQX_NODE_NAME=emqx@node1.emqx.io"
    ports:
      - 1883:1883
      - 8083:8083
      - 8084:8084
      - 8883:8883
      - 18083:18083
    volumes:
      - $PWD/emqx_data:/opt/emqx/data
    healthcheck:
      test: ["CMD", "/opt/emqx/bin/emqx", "ctl", "status"]
      interval: 5s
      timeout: 25s
      retries: 5
